web:
  build: .
  command: bin/web
  links:
   - postgres
   - redis
  ports:
   - "3000:3000"
  volumes:
   - .:/app
worker:
  build: .
  command: bin/worker
  links:
   - postgres
   - redis
  volumes:
   - .:/app
postgres:
  image: convox/postgres
redis:
  image: convox/redis
